services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: oficina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50" # usa no máximo meio núcleo de CPU

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25" # usa 1/4 do núcleo

volumes:
  postgres_data:
  pgadmin_data:
