services:
  postgres:
    image: postgres
    container_name: postgres_oficina
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: oficina_mecanica
